tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'

brew 'stow'
brew 'jq'
brew 'mackup'
brew 'mas'
brew 'neovim'
brew 'autojump'
brew 'zsh-autosuggestions'
brew 'tmux'
# brew 'npm' brew 'yarn'
brew 'n'
brew 'lazygit'
brew 'ripgrep'

cask 'figma'
cask 'firefox'
# cask 'google-chrome'
cask 'httpie'
cask 'imageoptim'
cask 'tableplus'
cask 'telegram-desktop'
# cask 'visual-studio-code'
cask 'localsend'
cask 'docker'
cask 'keka'

cask 'font-fira-code'
cask 'font-hack-nerd-font'
